### ISSUE TITLE
npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Eafy** [TuyaInc/tuyasmart-home-sdk-react-native#1]
请问npm安装的版本是多少，这边安装会出现这个问题：npm ERR! Maximum call stack size exceeded

**Comment by Eafy** [comment]
改用yarn add命令就可以了。。。

**Comment by Eafy** [comment]
npm install tuyasmart-home-sdk --save 
则会报上述错误。

**Comment by hughcoder** [comment]
now “ tuyasmart-home-sdk” only hava android source ,I suggest that you directly add the source code related to native in the example to your project
