### ISSUE TITLE
Type Error: Type Error: null is not an Object

### ISSUE THREAD

**Issue by THALLIVA** [TuyaInc/tuyasmart-home-sdk-react-native#12]
While working with React Native SDK, the installation process is completed without any Errors,
but when i try to start the app I get this error
![WhatsApp Image 2019-04-09 at 4 11 13 PM (1)](https://user-images.githubusercontent.com/29727173/55874222-63022480-5baf-11e9-8661-8542813e7a27.jpeg)

I followed the following method

I downloaded the Example file from https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/tree/master/Example 
and while running the file I got this error..
Commands I used for install and running
-> cd Example/
-> npm install
-> npm eject (after deleting android and iOS folders) 
-> npm start
-> react-native run-android

The app is installed in the Android Device but not working..

Also please do update the NPM packages to latest release..
Im using

-> react-native-cli: 2.0.1
-> react-native: 0.59.4
-> node -v
v8.12.0
-> npm -v
6.9.0

**Comment by THALLIVA** [comment]
On the Mobile

**Comment by hughcoder** [comment]
why you excute  the npm eject (after deleting android and iOS folders) ,don‘t delete anything，just -> npm install \-> npm start\-> react-native run-android  ,have a try  @THALLIVA

**Comment by tronginc** [comment]
don't delete anything or manual link **tuyasmart-home-sdk-react-native** to your project
