### ISSUE TITLE
[Android] crash when a device shared 

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#13]
A share for B an device, so the B's app crashed while A sharing success.

![image](https://user-images.githubusercontent.com/33952884/55928462-e882e480-5c42-11e9-82f2-cc6bbad12133.png)

Root caused **TuyaHomeManagerModule.kt:99**

    override fun onSharedGroupList(var1: List<GroupBean>) {
                val map = Arguments.createMap()
                map.putArray("groupBeans", 
        TuyaReactUtils.parseToWritableArray(JsonUtils.toJsonArray(var1)))
                map.putString("type", "onSharedGroupList");
                BridgeUtils.homeChange(reactApplicationContext, map, params.getString("homeId"))
    }

**Comment by hughcoder** [comment]
I will fix it

**Comment by hughcoder** [comment]
it's done
