### ISSUE TITLE
[iOS only] Error "permission validate failed" when calling TuyaShareApi.queryDevShareUserList

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#14]
I have to call TuyaShareApi.queryDevShareUserList({ devId }). On Android, It work!!! But on iOS, it log the error: **`permission validate failed`**

    TuyaShareApi.queryDevShareUserList({ devId })
        .then(data => console.log(data))
        .catch(err => console.log(err))

**Comment by iphone1945** [comment]
Have you set the appkey and appsecret along with the secure image?

**Comment by tronginc** [comment]
> Have you set the appkey and appsecret along with the secure image?
@iphone1945 
where and how I can set secure image for my app?
Why it only work on android
