### ISSUE TITLE
第一次尝试

### ISSUE THREAD

**Issue by JayricMok** [TuyaInc/tuyasmart-home-sdk-react-native#2]
更改尝试了这个sdk，当react-native link完了之后，发现有一些漏洞 `Failed to resolve: :tuyasmart-0.0.2` ，请问该如何解决呢？使用的react native 版本是 0.57.8

**Comment by tonyleeecn** [comment]
> 更改尝试了这个sdk，当react-native link完了之后，发现有一些漏洞 `Failed to resolve: :tuyasmart-0.0.2` ，请问该如何解决呢？使用的react native 版本是 0.57.8
您好，是否有更详细的gradle日志？

**Comment by tonyleeecn** [comment]
> ![image](https://user-images.githubusercontent.com/6957533/51652480-c1fdc780-1fca-11e9-9afd-7dd55d956195.png)
> 我怀疑是sdk找不到他的aar，应该如何处置

请参考 https://tuyakae.gitbook.io/tuyasmart-home-sdk-react-native/integrated
