### ISSUE TITLE
Running the android app not working

### ISSUE THREAD

**Issue by macthorman** [TuyaInc/tuyasmart-home-sdk-react-native#21]
I run "react-native run-android" in the "Example" folder and the process starts, but I get the following error message and the build process fails:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'TuyaRnDemo'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.tuya.smart:buildsdk:0.1.5-SNAPSHOT.
     Required by:
         project :
      > Could not resolve com.tuya.smart:buildsdk:0.1.5-SNAPSHOT.
         > Unable to load Maven meta-data from http://112.124.7.102:8081/nexus/content/repositories/releases/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://112.124.7.102:8081/nexus/content/repositories/releases/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://112.124.7.102:8081/nexus/content/repositories/releases/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml'.
                  > Connect to 112.124.7.102:8081 [/112.124.7.102] failed: Connection timed out: connect
      > Could not resolve com.tuya.smart:buildsdk:0.1.5-SNAPSHOT.
         > Unable to load Maven meta-data from http://112.124.7.102:8081/nexus/content/repositories/central/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://112.124.7.102:8081/nexus/content/repositories/central/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://112.124.7.102:8081/nexus/content/repositories/central/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml'.
                  > Connect to 112.124.7.102:8081 [/112.124.7.102] failed: Connection timed out: connect
      > Could not resolve com.tuya.smart:buildsdk:0.1.5-SNAPSHOT.
         > Unable to load Maven meta-data from http://112.124.7.102:8081/nexus/content/groups/public/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://112.124.7.102:8081/nexus/content/groups/public/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://112.124.7.102:8081/nexus/content/groups/public/com/tuya/smart/buildsdk/0.1.5-SNAPSHOT/maven-metadata.xml'.
                  > Connect to 112.124.7.102:8081 [/112.124.7.102] failed: Connection timed out: connect
`

Could you please help me and guide me through how I can get the react-native example to work?

**Comment by hughcoder** [comment]
Drag down the latest code again

**Comment by hughcoder** [comment]
pull
