### ISSUE TITLE
Support RN 0.59.0+ for 64bit

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#23]
> Starting August 1, 2019:
> All new apps and app updates that include native code are required to provide 64-bit versions in addition to 32-bit versions when publishing to Google Play.
> Extension: Google Play will continue to accept 32-bit only updates to existing games that use Unity 5.6.x or older until August 2021.

But when I build it with React-Native 0.59.0+, the SDK throw so much error of Kotlin code

**Comment by linqwFmt** [comment]
try 0.59
