### ISSUE TITLE
TuyaDeviceApi.getDp not working on Android

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#25]
Hello, 
Today I need get dpValue for status reporting, so I call the function 

    TuyaDeviceApi.getDp({ devId, dpId })
        .then((status) => console.log(status))
        .catch((e) => console.log(e));

It's works on iOS. So on Android it throw the error

![image](https://user-images.githubusercontent.com/33952884/57925862-db0cea00-78d3-11e9-99c8-524518cb4352.png)

**Comment by linqwFmt** [comment]
fixBugs
