### ISSUE TITLE
React Native Android Folder not found..

### ISSUE THREAD

**Issue by THALLIVA** [TuyaInc/tuyasmart-home-sdk-react-native#28]
I followed this procedure and I am failing to achieve the desired result..

I followed this procedure..

-> cd Example
-> sudo npm install
-> sudo npm start
-> sudo react-native run-android

I am not deleting or doing a manual link to the SDK..

Just wanted to run the React-Native Example App..
I have attached the screenshot of the following problem..

![Screenshot 2019-06-14 at 3 00 05 PM](https://user-images.githubusercontent.com/29727173/59499894-fc063200-8eb5-11e9-9d6f-19bf29ec3b3f.png)

**Comment by THALLIVA** [comment]
Forgot to mention
react-native-cli: 2.0.1
react-native: 0.58.0
npm: : 6.9.0

**Comment by linqwFmt** [comment]
build.gradle 
remove wrapper
// task wrapper(type: Wrapper) {
//     gradleVersion = '4.4'
//     distributionUrl = distributionUrl.replace("bin", "all")
// }

**Comment by THALLIVA** [comment]
I removed the wrapper but still I'm getting this Error..
![Screenshot 2019-06-19 at 5 45 44 PM](https://user-images.githubusercontent.com/29727173/59764858-4aeb0780-92ba-11e9-9f78-e088e58a9af3.png)

**Comment by linqwFmt** [comment]
react-native upgrade

**Comment by THALLIVA** [comment]
Did that too...
But still getting the Error..

downgraded the JDK version to 9 but still getting this error..
Gradle 4.7 supports JDK till 10..
![Screenshot 2019-06-19 at 6 15 07 PM](https://user-images.githubusercontent.com/29727173/59766876-bb942300-92be-11e9-93b0-9e4c862781cb.png)

**Comment by linqwFmt** [comment]
react-native upgrade

**Comment by THALLIVA** [comment]
Did that friend.. It gave me the above error..

**Comment by h4run** [comment]
I still have the same issue
