### ISSUE TITLE
[Android] TuyaActivatorApi.initActivator invoke callback error

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#3]
Hello, I've built [Example ](https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/tree/master/Example) app. Then I got the error when calling `TuyaActivatorApi.initActivator`

    ReactNativeJS: The callback initActivator() exists in module TuyaActivatorModule, but only one callback may be registered to a function in a native module.

I think this happens on android when invoke the same callback in native **more than once..**

Here is the screenshot
![alt](https://i.imgur.com/PQPpAMs.png)

[JS code permalink](https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/blob/f9a3f30452dffcc2571d404912630fb2a98f322f/Example/App/pages/configPages/ConfigPage.js#L57): 

    TuyaActivatorApi.initActivator({
        // 配网
        homeId: this.state.homeId,
        ssid: this.state.ssid,
        password: this.state.wifipassword,
        time: this.state.maxTime,
        type: 'TY_EZ',
      })
        .then((data) => {
          // console.log('----->data', data);
          // console.warn('PEIWANGCGON');

          this.setState({
            progresstime: 10,
            state: 'success',
            dev: data,
            mark: false,
            connecting: false,
            error: false,
          })
          this.props.navigation.navigate('scan', {
            dev: this.state.dev,
            key: this.props.navigation.state.params.key,
            func: (devId) => {
              this.props.navigation.pop()
              this.props.navigation.state.params.func(devId)
            },
          })
          this.stop()
        })
        .catch((error) => {
          console.log('---config err', error)
          this.refs.toast.show(error.toString().slice(7))
          this.setState({
            progresstime: 10,
            error: true,
            state: '',
            mark: false,
            connecting: false,
          })
        })

**Comment by tonyleeecn** [comment]
This happens on android if you invoke the same Callback in native more than once. We are trying to find why this happend.

**Comment by BilalS10** [comment]
Hello,
@tronginc , can you state the steps on how to use the example app?
cause i tried multiple methods but in vain. 
When i create a new project and do it, it gives an error of package not found of "my project name".
so i initiated a project in the example folder itself and still it gave an error related to the packages.
Kindly let me know the proper steps to create an example app.

**Comment by tronginc** [comment]
> Hello,
> @tronginc , can you state the steps on how to use the example app?
> cause i tried multiple methods but in vain.
> When i create a new project and do it, it gives an error of package not found of "my project name".
> so i initiated a project in the example folder itself and still it gave an error related to the packages.
> Kindly let me know the proper steps to create an example app.

I just download /Example folder, `yarn install` and `react-native run-android`

**Comment by BilalS10** [comment]
> > Hello,
> > @tronginc , can you state the steps on how to use the example app?
> > cause i tried multiple methods but in vain.
> > When i create a new project and do it, it gives an error of package not found of "my project name".
> > so i initiated a project in the example folder itself and still it gave an error related to the packages.
> > Kindly let me know the proper steps to create an example app.
> 
> I just download [Example ](https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/tree/master/Example) folder, `yarn install` and `react-native run-android`

I did the same. 
But, after 'yarn install' , the other command `react-native run-android` is not working and throwing me an error of -> Android project not found. Maybe run react-native android first?

**Comment by tronginc** [comment]
To resolve the issue please upgrade the react-native package.

1. Go to the **Project root.**

2. Upgrade the React native package in the **Command Prompt** by typing: `react-native upgrade`

Then Accept to update all the Files by typing y (Yes) in the Command Prompt.

**android/settings.gradle**

    rootProject.name = 'TuyaRnDemo'
    include ':tuyasmart-home-sdk'
    project(':tuyasmart-home-sdk').projectDir = new File(rootProject.projectDir, '../node_modules/tuyasmart-home-sdk/android')
    include ':react-native-svg', ':package'
    project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')
    include ':react-native-wheel-picker'
    project(':react-native-wheel-picker').projectDir = new File(settingsDir, '../node_modules/react-native-wheel-picker/android')

    include ':app'

**android/build.gradle**

     // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        ext {
            buildToolsVersion = "27.0.3"
            minSdkVersion = 16
            compileSdkVersion = 27
            targetSdkVersion = 26
            supportLibVersion = "27.1.1"
        }
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.1.4'
    
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
    
    allprojects {
        repositories {
            google()
            mavenLocal()
            jcenter()
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }
        }
    }
    
    
    task wrapper(type: Wrapper) {
        gradleVersion = '4.4'
        distributionUrl = distributionUrl.replace("bin", "all")
    }

**android/app/build.gradle**


    apply plugin: "com.android.application"
    
    import com.android.build.OutputFile
    
    /**
     * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
     * and bundleReleaseJsAndAssets).
     * These basically call `react-native bundle` with the correct arguments during the Android build
     * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
     * bundle directly from the development server. Below you can see all the possible configurations
     * and their defaults. If you decide to add a configuration block, make sure to add it before the
     * `apply from: "../../node_modules/react-native/react.gradle"` line.
     *
     * project.ext.react = [
     *   // the name of the generated asset file containing your JS bundle
     *   bundleAssetName: "index.android.bundle",
     *
     *   // the entry file for bundle generation
     *   entryFile: "index.android.js",
     *
     *   // whether to bundle JS and assets in debug mode
     *   bundleInDebug: false,
     *
     *   // whether to bundle JS and assets in release mode
     *   bundleInRelease: true,
     *
     *   // whether to bundle JS and assets in another build variant (if configured).
     *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
     *   // The configuration property can be in the following formats
     *   //         'bundleIn${productFlavor}${buildType}'
     *   //         'bundleIn${buildType}'
     *   // bundleInFreeDebug: true,
     *   // bundleInPaidRelease: true,
     *   // bundleInBeta: true,
     *
     *   // whether to disable dev mode in custom build variants (by default only disabled in release)
     *   // for example: to disable dev mode in the staging build type (if configured)
     *   devDisabledInStaging: true,
     *   // The configuration property can be in the following formats
     *   //         'devDisabledIn${productFlavor}${buildType}'
     *   //         'devDisabledIn${buildType}'
     *
     *   // the root of your project, i.e. where "package.json" lives
     *   root: "../../",
     *
     *   // where to put the JS bundle asset in debug mode
     *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
     *
     *   // where to put the JS bundle asset in release mode
     *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
     *
     *   // where to put drawable resources / React Native assets, e.g. the ones you use via
     *   // require('./image.png')), in debug mode
     *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
     *
     *   // where to put drawable resources / React Native assets, e.g. the ones you use via
     *   // require('./image.png')), in release mode
     *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
     *
     *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
     *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
     *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
     *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
     *   // for example, you might want to remove it from here.
     *   inputExcludes: ["android/**", "ios/**"],
     *
     *   // override which node gets called and with what additional arguments
     *   nodeExecutableAndArgs: ["node"],
     *
     *   // supply additional arguments to the packager
     *   extraPackagerArgs: []
     * ]
     */
    
    project.ext.react = [
        entryFile: "index.js"
    ]
    
    apply from: "../../node_modules/react-native/react.gradle"
    
    /**
     * Set this to true to create two separate APKs instead of one:
     *   - An APK that only works on ARM devices
     *   - An APK that only works on x86 devices
     * The advantage is the size of the APK is reduced by about 4MB.
     * Upload all the APKs to the Play Store and people will download
     * the correct one based on the CPU architecture of their device.
     */
    def enableSeparateBuildPerCPUArchitecture = false
    
    /**
     * Run Proguard to shrink the Java bytecode in release builds.
     */
    def enableProguardInReleaseBuilds = false
    
    android {
        compileSdkVersion rootProject.ext.compileSdkVersion
        buildToolsVersion rootProject.ext.buildToolsVersion
    
        defaultConfig {
            applicationId "com.tuyarndemo"
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 1
            versionName "1.0"
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
            multiDexEnabled true
        }
        splits {
            abi {
                reset()
                enable enableSeparateBuildPerCPUArchitecture
                universalApk false  // If true, also generate a universal APK
                include "armeabi-v7a", "x86"
            }
        }
        buildTypes {
            release {
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            }
        }
        // applicationVariants are e.g. debug, release
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                // For each separate APK per architecture, set a unique version code as described here:
                // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
                def versionCodes = ["armeabi-v7a":1, "x86":2]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {  // null for the universal-debug, universal-release variants
                    output.versionCodeOverride =
                            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                }
            }
        }
    }
    
    dependencies {
        compile project(':tuyasmart-home-sdk')
        implementation fileTree(dir: "libs", include: ["*.jar"])
        implementation 'com.android.support:appcompat-v7:26.1.0'
        implementation 'com.android.support:multidex:1.0.1'
        api "org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.41"
        implementation "com.facebook.react:react-native:+"  // From node_modules
        implementation project(':react-native-wheel-picker')
        implementation project(':react-native-svg')
        implementation 'com.android.support:multidex:1.0.3'
        compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
        compile 'io.reactivex.rxjava2:rxjava:2.1.7'
        compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
        implementation 'com.alibaba:fastjson:1.1.68.android'
        compile 'com.squareup.okhttp3:okhttp-urlconnection:3.6.0'
    }
    
    
    // Run this once to be able to run the application with BUCK
    // puts all compile dependencies into folder libs for BUCK to use
    task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
    }
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../node_modules/react-native/android"
        }
        mavenCentral()
        google()
        flatDir {
            dirs 'libs'
        }
    }


**MainApplication.java**

    package com.tuyarndemo;
  
    import android.app.Application;
  
    import com.facebook.react.ReactApplication;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;
    import com.facebook.soloader.SoLoader;
    import com.horcrux.svg.SvgPackage;
    import com.tuya.rnsdk.TuyaRNSDKPackage;
    import com.zyu.ReactNativeWheelPickerPackage;
    import java.util.Arrays;
    import java.util.List;
  
    public class MainApplication extends Application implements ReactApplication {
  
      private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }
  
        @Override
        protected List<ReactPackage> getPackages() {
          return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
                  new TuyaRNSDKPackage(),
                  new SvgPackage(),
                  new ReactNativeWheelPickerPackage()
          );
        }
  
        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };
  
      @Override
      public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
      }
  
      @Override
      public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
      }
    }

**Comment by BilalS10** [comment]
Thank you @tronginc .
I followed all the steps and the app is now installed on my phone.
Seemed like the gradle was not compatible with the sdk .
Though, the app got installed, it immediately stops and goes in the background and nothing happens.
And there is no error seen on the command line from where I am running nor on the js server which runs.
What is the first screen that should load in this example app?
Thank you for your help!:)

**Comment by tronginc** [comment]
I think If you connect your phone to your computer and type `adb logcat | findstr com.tuyarndemo`
Then reopen the app, you will see what happened
