### ISSUE TITLE
[Android only] productBean is null if an user have more than one device is the same productId

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#3]
Hello, I have a issue when I get **deviceList** by calling `TuyaHomeApi.queryRoomList`. So if I have more than one device is the same productId, the field schema is empty and productBean is null.

In the picture bellow, I have 2 devices is the same productId `XFD2nSDKxFlGV5sV`, the first devId: `12120404840d8e99bffa` and the second devId: `12120404840d8e99c1e9`

My account phoneNumber: 0347906878 and country code: +84

![image](https://user-images.githubusercontent.com/33952884/55525300-cde8c280-56ba-11e9-847d-1645a10a15db.png)
![image](https://user-images.githubusercontent.com/33952884/55525313-e1942900-56ba-11e9-91ed-14032d49249c.png)

**Comment by hughcoder** [comment]
maybe you can try TuyaHomeDataManagerApi.getRoomDeviceList to get more information

**Comment by tronginc** [comment]
> maybe you can try TuyaHomeDataManagerApi.getRoomDeviceList to get more information

So If we want to have all device on all room, we need to loop through all room and call TuyaHomeDataManagerApi.getRoomDeviceList?
Because I need all deviceList on all room to control voice, create scene, etc...
And... on android, TuyaHomeDataManagerApi.getRoomDeviceList always return `[]`

**Comment by hughcoder** [comment]
before you use other method about family  ,you should use this     TuyaHomeApi.getHomeDetail({
    homeId:'',
}).then(data=>{}).catch(e=>{}) first ,Please refer to the document first

**Comment by tronginc** [comment]
Sure, I call `TuyaHomeApi.getHomeDetail` after `TuyaHomeManagerApi.queryHomeList`. But the the issue still happened. Schema is empty and productBean is null when deviceList have more than one device is the same **productId**

**Comment by tronginc** [comment]
It's also happend on **`sharedDeviceList`**  queried from **`TuyaHomeApi.getHomeDetail`**

**Comment by hughcoder** [comment]
it's done
