### ISSUE TITLE
'TuyaSmartDeviceKit/TuyaSmartActivator.h' file not found - IOS

### ISSUE THREAD

**Issue by prasadpilla** [TuyaInc/tuyasmart-home-sdk-react-native#30]
Hi,

I have followed all the instructions provided in the README. 

Getting the error when I build the project from Xcode "'TuyaSmartDeviceKit/TuyaSmartActivator.h' file not found ".

![image](https://user-images.githubusercontent.com/14332320/60098193-972ebf80-9772-11e9-8c42-2062c628a8f3.png)

I am not clear on the instruction below, I have placed the contents of that folder into the root directory of my react native project.
"2. Drag the files in TuyaRNSDK to your project."

Let me know if I need to do something different.

**Comment by prasadpilla** [comment]
Hey there,

any update on this?

**Comment by linqwFmt** [comment]
try 0.59 branch

**Comment by theecn** [comment]
xCode12.5仍然有这个问题，请问修复了？ rn0.59分支也不行
