### ISSUE TITLE
null is not an object(evaluating 'CoreNativeApi.initWithOptions')

### ISSUE THREAD

**Issue by Mohaiyo** [TuyaInc/tuyasmart-home-sdk-react-native#31]
我直接从项目仓库clone下来的文件，按照readme的指引 添加了appKey、appScrect以及安全图片，安装相关的依赖之后，react-native run-ios直接报这个错误，原生模块引不进来是啥原因？  ps:中间react-native upgrade了一次。
[
![企业微信截图_79360cae-aad5-4c6a-ac64-67a5c2c39fc6](https://user-images.githubusercontent.com/22421509/61118288-00306a00-a4cb-11e9-89cb-04845372b49d.png)
](url)

**Comment by linqwFmt** [comment]
0.59

**Comment by adnan1naeem** [comment]
i am facing same error on react-native v0.61.0 on ios can you please explain how to resolve it

**Comment by linqwFmt** [comment]
I'm sorry. I'll check if there's a problem. I'll reply later

**Comment by linqwFmt** [comment]
Can you describe the operation steps in detail

**Comment by adnan1naeem** [comment]
> Can you describe the operation steps in detail

i  added latest version of react-native 0.61.5 and followed the documentation with the following steps for ios:
[link](https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/blob/master/compileSdk.md
)

when i call method nativemodules.TuyaCoreApi .it provides empty object of nativemodules.There is no module  tuyaCoreApI inside the sdk in ios but android works fine.
please see line number 2 of following url.It provides empty nativemodules object in ios
[link](https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/blob/master/sdk/lib/TuyaCoreApi.js)
