### ISSUE TITLE
TuyaUserApi.getValidateCode throw Error permission validation failed!

### ISSUE THREAD

**Issue by Mohaiyo** [TuyaInc/tuyasmart-home-sdk-react-native#36]
![permission](https://user-images.githubusercontent.com/22421509/61944460-48be4c00-afd0-11e9-9ec9-625d745ea34d.png)
![res](https://user-images.githubusercontent.com/22421509/61945116-c6368c00-afd1-11e9-8c59-94cffded2b40.png)
![bundleId](https://user-images.githubusercontent.com/22421509/61945131-cb93d680-afd1-11e9-9b28-91c130b6b659.png)
I had config the appKey appSecret t_s.bmp and bundleId,but it still throw the Error.

**Comment by linqwFmt** [comment]
Is image and key configured?

**Comment by linqwFmt** [comment]
You operate on that branch.

**Comment by Mohaiyo** [comment]
@linqwFmt 0.59rn

**Comment by linqwFmt** [comment]
Is your key configured in constant. js?

**Comment by Mohaiyo** [comment]
![appDelegate](https://user-images.githubusercontent.com/22421509/62449046-e1f11d80-b79b-11e9-899a-f18ef956b8b8.png)
Yes,I config my key both in constant.js and AppDelegate.m.

**Comment by linqwFmt** [comment]
在constant.js 里面 在App 目录下



------------------ 原始邮件 ------------------
发件人: "Ohaiyo"<notifications@github.com>; 
发送时间: 2019年8月5日(星期一) 下午4:15
收件人: "TuyaInc/tuyasmart-home-sdk-react-native"<tuyasmart-home-sdk-react-native@noreply.github.com>; 
抄送: "1105896230"<1105896230@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [TuyaInc/tuyasmart-home-sdk-react-native]TuyaUserApi.getValidateCode throw Error permission validation failed! (#36)





 是的，我在constant.js和AppDelegate.m中配置我的密钥。
 
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by linqwFmt** [comment]
Security Image and bundle Id check
