### ISSUE TITLE
React Demo App - Authentication

### ISSUE THREAD

**Issue by carlosvirreira** [TuyaInc/tuyasmart-home-sdk-react-native#37]
Hi, I installed the Demo app on my computer for testing, however, I cannot get past the splash screen and login screen. 

How can I get a user to test the rest of the views here?

![Screenshot 2019-08-01 at 17 46 14](https://user-images.githubusercontent.com/12449255/62307772-7dc11780-b484-11e9-97bf-9d840a64a235.png)

is there a demo user I can use to go to the next step?

Thank you so much in advance

**Comment by linqwFmt** [comment]
Is image and key configured?

**Comment by linqwFmt** [comment]
You operate on that branch.

**Comment by carlosvirreira** [comment]
Hi @linqwFmt - image and key are configured indeed.

I get this message "permission validation failed ."

![Simulator Screen Shot - iPhone X - 2019-08-02 at 12 00 17](https://user-images.githubusercontent.com/12449255/62360835-fc1bc900-b519-11e9-8f0c-37035e04fa3b.png)

Follow the documentation and image and key configured , I would love it if you could point me in the right direction for the next step. Unfortunately I do not speak any Chinese, however, hope that after authenticating I can change it somewhere on the UI.

Thank you so much @linqwFmt

**Comment by linqwFmt** [comment]
Take Android as an example. Android Assets joins the security image build. gradle to modify the application Id constant. JS you applied for to fill in the key of your application.

try to run on 0.59 branch

**Comment by carlosvirreira** [comment]
Will share this with our team, thanks for your reply!

By the way, I would like to consult a few things with you in terms of building a Tuya IOT app with react SDK. Perhaps you could help me (for a fee) if you are interested could you mail me to carlos@whale-agency.com please? Just to have your contact.

**Comment by carlosvirreira** [comment]
> Take Android as an example. Android Assets joins the security image build. gradle to modify the application Id constant. JS you applied for to fill in the key of your application.
> 
> try to run on 0.59 branch

 
android demo not work at all the app crash immediately after lunch.

demo is based on .58 react-native version.

**Comment by linqwFmt** [comment]
https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/tree/rn0.59

**Comment by carlosvirreira** [comment]
Thank you, do you have an idea of when we can expect a stable release? Is it advised to use the react SDK or better the ios/android separate ones?

**Comment by linqwFmt** [comment]
ios/android

**Comment by pckz** [comment]
@carlosvirreira @linqwFmt when dou you expect a stable release for React Native?
thanks!
