### ISSUE TITLE
TuyaDeviceApi.unRegisterDevListener seem not working (android)

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#4]
After I call TuyaDeviceApi.unRegisterDevListener({ devId }), the app continues call onDpUpdate when I control on device.

**Comment by hughcoder** [comment]
it's fix In the latest version ,you can pull the latest code

**Comment by hughcoder** [comment]
@tronginc

**Comment by tronginc** [comment]
Fixed in lasted version. Thank @hughcoder
