### ISSUE TITLE
TuyaDeviceApi.registerDevListener didn't works on iOS, but works on Android

### ISSUE THREAD

**Issue by ThoMiDev** [TuyaInc/tuyasmart-home-sdk-react-native#40]
`TuyaDeviceApi.registerDevListener` function only works on Android. On iOS:

![image](https://user-images.githubusercontent.com/49932599/65479160-8fd49a80-deb6-11e9-8dc0-f98b64182bf5.png)

    TuyaDeviceApi.registerDevListener(
        { devId: device.id },
        console.warn,
        console.warn,
        console.warn,
        console.warn,
        console.warn,
      );

**Comment by linqwFmt** [comment]
fix
