### ISSUE TITLE
react-native-wheel-picker出现这个Unexpected reserved type number

### ISSUE THREAD

**Issue by ChinaYangYan** [TuyaInc/tuyasmart-home-sdk-react-native#44]
![企业微信截图_15770645058763](https://user-images.githubusercontent.com/22555812/71330242-c201a100-2566-11ea-8a1a-8219392d22a6.png)

**Comment by linqwFmt** [comment]
import PropTypes from 'prop-types';
 try

**Comment by ChinaYangYan** [comment]
这是引用的第三包里面源码编译时报的错，无法修改源码

**Comment by ChinaYangYan** [comment]
![image](https://user-images.githubusercontent.com/22555812/71388588-f68f5e80-2633-11ea-95ec-d52a626954cd.png)
已经有添加了

**Comment by linqwFmt** [comment]
react-native 外部是多少

**Comment by ChinaYangYan** [comment]
"react": "16.8.6",
    "react-native": "0.59.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-picker": "^4.3.7",
    "react-native-root-toast": "^3.1.2",
    "react-native-scrollable-tab-view": "0.10.0",
    "react-native-tab-navigator": "^0.3.4",
    "react-native-wheel-picker": "^1.2.0",
    "react-navigation": "2.11.2",
    "react-navigation-redux-helpers": "^2.0.8",
    "react-redux": "^5.1.0",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.3",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rxjs": "^6.3.3"



react-native -v
react-native-cli: 2.0.1

**Comment by ChinaYangYan** [comment]
\tuyasmart-home>react-native -v
react-native-cli: 2.0.1
react-native: 0.59.0

**Comment by linqwFmt** [comment]
try

**Comment by linqwFmt** [comment]
I changed picker. You're trying
