### ISSUE TITLE
TuyaDeviceApi.registerDevListener - event: onDpUpdate - doesn't work correctly on iOS

### ISSUE THREAD

**Issue by Ashalbulk** [TuyaInc/tuyasmart-home-sdk-react-native#46]
```TuyaDeviceApi.registerDevListener``` - event: ```onDpUpdate``` - doesn't work correctly on iOS

On android, if we change dp we receive just one event ```onDpUpdate``` with everything necessary inside. 
On iOS, if we change dp we receive a lot of events with separated changes and a lot of them are duplicates of the previous one, sometimes it can be more than **100 events at once**. It looks like a big mess and works definitely not correct. 

Could you please provide the same behaviour as on android? It is a **very important** point, cause we have **a lot of speed issues on iOS according to this**.

**Comment by linqwFmt** [comment]
fix
