### ISSUE TITLE
implementation(name: "tuyasmart-3.10.0", ext: "aar")

### ISSUE THREAD

**Issue by Ashalbulk** [TuyaInc/tuyasmart-home-sdk-react-native#47]
After this commit: https://github.com/TuyaInc/tuyasmart-home-sdk-react-native/commit/253c644f8fb19eccaf28aefb73211b8fef709fc4 
Our system can't file **tuyasmart-3.10.0.aar**. I think that you **forgot** to add this file. Could you **add this file**, please?

**Comment by linqwFmt** [comment]
i am sorry I updated.
