### ISSUE TITLE
[iOS only] "background is illegal" throw when calling TuyaSceneApi.createScene

### ISSUE THREAD

**Issue by tronginc** [TuyaInc/tuyasmart-home-sdk-react-native#6]
When I call TuyaSceneApi.createScene  with params:

    const params = {
        homeId: 6114948,
	    name: "test nè",
	    stickyOnTop: false,
	    tasks: [{
		dpId: 1,
		value: true,
		devId: "22553644840d8ea14462"
	    }],
	    matchType: 'MATCH_TYPE_OR',
	    devIds: ["22553644840d8ea14462"],
	    background: 'https://images.tuyacn.com/smart/rule/cover/bedroom.png',
	};
    TuyaSceneApi.createScene(params);

On Android, It's work, but on iOS, it throw error: "background is illegal"

**Comment by tronginc** [comment]
It work if I set **`background`** to `""`

**Comment by iphone1945** [comment]
> When I call TuyaSceneApi.createScene with params:
> 
> ```
> const params = {
>     homeId: 6114948,
>     name: "test nè",
>     stickyOnTop: false,
>     tasks: [{
> 	dpId: 1,
> 	value: true,
> 	devId: "22553644840d8ea14462"
>     }],
>     matchType: 'MATCH_TYPE_OR',
>     devIds: ["22553644840d8ea14462"],
>     background: 'https://images.tuyacn.com/smart/rule/cover/bedroom.png',
> };
> TuyaSceneApi.createScene(params);
> ```
> On Android, It's work, but on iOS, it throw error: "background is illegal"

It worked when I set the almost the same params. Can u figure out the params when the native method addNewSceneWithName called?

**Comment by tronginc** [comment]
> > When I call TuyaSceneApi.createScene with params:
> > ```
> > const params = {
> >     homeId: 6114948,
> >     name: "test nè",
> >     stickyOnTop: false,
> >     tasks: [{
> > 	dpId: 1,
> > 	value: true,
> > 	devId: "22553644840d8ea14462"
> >     }],
> >     matchType: 'MATCH_TYPE_OR',
> >     devIds: ["22553644840d8ea14462"],
> >     background: 'https://images.tuyacn.com/smart/rule/cover/bedroom.png',
> > };
> > TuyaSceneApi.createScene(params);
> > ```
> > On Android, It's work, but on iOS, it throw error: "background is illegal"
> 
> It worked when I set the almost the same params. Can u figure out the params when the native method addNewSceneWithName called?

It work only on Android. IOS throw error: "background is illegal"
It work on iOS if I set background to ""

**Comment by iphone1945** [comment]
> > > When I call TuyaSceneApi.createScene with params:
> > > ```
> > > const params = {
> > >     homeId: 6114948,
> > >     name: "test nè",
> > >     stickyOnTop: false,
> > >     tasks: [{
> > > 	dpId: 1,
> > > 	value: true,
> > > 	devId: "22553644840d8ea14462"
> > >     }],
> > >     matchType: 'MATCH_TYPE_OR',
> > >     devIds: ["22553644840d8ea14462"],
> > >     background: 'https://images.tuyacn.com/smart/rule/cover/bedroom.png',
> > > };
> > > TuyaSceneApi.createScene(params);
> > > ```
> > > On Android, It's work, but on iOS, it throw error: "background is illegal"
> > 
> > 
> > It worked when I set the almost the same params. Can u figure out the params when the native method addNewSceneWithName called?
> 
> It work only on Android. IOS throw error: "background is illegal"
> It work on iOS if I set background to ""

I used almost the same params to test again, it worked.  Paste the error log here, May be something else went wrong.

**Comment by tronginc** [comment]
function* createNewScene(action) {
    	try {
    		const { params, isAutoScene } = action;
    		console.log('%c START createNewScene Saga isAutoScene: ' + isAutoScene , 'font-size: 30px; color: #FFF; background: green');
    		const data = yield call(isAutoScene ? TuyaSceneApi.createAutoScene : TuyaSceneApi.createScene, params);
    		console.log(data);
    		yield put({ type: types.sceneTypes.SCENE_ADD_SCENE_SUCCESS, data });
    		yield put({ type: types.sceneTypes.SCENE_GET_ALL_SCENE_START })
    	}
    	catch (e) {
    		console.log(action.params);
    		console.log(e.code);
    		console.log(e.key);
    		console.log(e.framesToPop);
    		console.log(e.message);
    		console.log(e);
    		console.log(JSON.stringify(e));
    		yield put({ type: types.notifyTypes.NOTIFY_NEW, notifyType: 'error', notifyMessage: e.message });
    		yield put({ type: types.sceneTypes.SCENE_ADD_SCENE_ERROR })
    	}
    	finally {
    		console.log('%c END createNewScene Saga', 'font-size: 30px; color: #FFF; background: green');
    	}
    }

Here is my logs:

params:


    {
      "homeId": 6149523,
      "name": "Ahuhu",
      "stickyOnTop": false,
      "tasks": [
        {
          "dpId": 1,
          "value": true,
          "dpName": "Đèn màu",
          "roomName": "Phòng khách",
          "devName": "Đèn nhiều màu nè",
          "devId": "22553644840d8ea14462",
          "isSelected": false
        }
      ],
      "matchType": "MATCH_TYPE_OR",
      "devIds": [
        "22553644840d8ea14462"
      ],
      "background": "https://images.tuyacn.com/smart/rule/cover/bedroom.png"
    }

code: 1501,
framesToPop: 1,
message: background is illegal
{"framesToPop":1,"code":"1501","nativeStackIOS":["0   ThoMi                               0x0000000104c76c34 RCTJSErrorFromCodeMessageAndNSError + 152","1   ThoMi                               0x0000000104c1c53c __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.218 + 176","2   ThoMi                               0x00000001048ca21c +[TuyaRNUtils rejecterWithError:handler:] + 324","3   ThoMi                               0x00000001048d2af8 __51-[TuyaRNSceneModule createScene:resolver:rejecter:]_block_invoke.264 + 100","4   ThoMi                               0x0000000104f75f90 __42-[TuyaApi requestSuccess:response:object:]_block_invoke.127 + 100","5   libdispatch.dylib                   0x000000018ef6d6c8 <redacted> + 24","6   libdispatch.dylib                   0x000000018ef6e484 <redacted> + 16","7   libdispatch.dylib                   0x000000018ef1a9a4 <redacted> + 1068","8   CoreFoundation                      0x000000018f4c5ce4 <redacted> + 12","9   CoreFoundation                      0x000000018f4c0bac <redacted> + 1964","10  CoreFoundation                      0x000000018f4c00e0 CFRunLoopRunSpecific + 436","11  GraphicsServices                    0x0000000191739584 GSEventRunModal + 100","12  UIKitCore                           0x00000001bc6d4c00 UIApplicationMain + 212","13  ThoMi                               0x00000001048be7d8 main + 124","14  libdyld.dylib                       0x000000018ef7ebb4 <redacted> + 4"],"domain":"com.tuya.www","userInfo":{"NSLocalizedFailureReason":"ILLEGAL","NSLocalizedDescription":"background is illegal"}}

**Comment by iphone1945** [comment]
Are you sure the param "background" in android is the same as "https://images.tuyacn.com/smart/rule/cover/bedroom.png"?

> > > > When I call TuyaSceneApi.createScene with params:
> > > > ```
> > > > const params = {
> > > >     homeId: 6114948,
> > > >     name: "test nè",
> > > >     stickyOnTop: false,
> > > >     tasks: [{
> > > > 	dpId: 1,
> > > > 	value: true,
> > > > 	devId: "22553644840d8ea14462"
> > > >     }],
> > > >     matchType: 'MATCH_TYPE_OR',
> > > >     devIds: ["22553644840d8ea14462"],
> > > >     background: 'https://images.tuyacn.com/smart/rule/cover/bedroom.png',
> > > > };
> > > > TuyaSceneApi.createScene(params);
> > > > ```
> > > > On Android, It's work, but on iOS, it throw error: "background is illegal"
> > > 
> > > 
> > > It worked when I set the almost the same params. Can u figure out the params when the native method addNewSceneWithName called?
> > 
> > 
> > It work only on Android. IOS throw error: "background is illegal"
> > It work on iOS if I set background to ""
> 
> I used almost the same params to test again, it worked. Paste the error log here, May be something else went wrong.

Are you sure the param "background" in android is the same as "https://images.tuyacn.com/smart/rule/cover/bedroom.png"?

**Comment by iphone1945** [comment]
You should use "https://images.tuyaus.com/smart/rule/cover/bedroom.png" instead of "https://images.tuyacn.com/smart/rule/cover/bedroom.png"
